-- CRUD Operations for inventorylist

-- INSERT INTO inventorylist
INSERT INTO inventorylist (
  INVENTORY_NAME, PRODUCT_NAME, PRODUCT_NAME_1, PRODUCT_NAME_2, PRODUCT_NAME_3,
  PRODUCT_PORTION, PRODUCT_PORTION_1, PRODUCT_PORTION_2, PRODUCT_PORTION_3,
  QTY_DATA, LOW_STOCK_THRESHOLD, RESTOCK_QTY, AUTO_ORDER, SUPPLIER,
  PRODUCT_TYPE, PLU, LAST_UPDATE
) VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8, $9,
  $10, $11, $12, $13, $14,
  $15, $16, CURRENT_DATE
) ON CONFLICT (INVENTORY_NAME) DO UPDATE SET
  PRODUCT_NAME = $2,
  PRODUCT_NAME_1 = $3,
  PRODUCT_NAME_2 = $4,
  PRODUCT_NAME_3 = $5,
  PRODUCT_PORTION = $6,
  PRODUCT_PORTION_1 = $7,
  PRODUCT_PORTION_2 = $8,
  PRODUCT_PORTION_3 = $9,
  QTY_DATA = $10,
  LOW_STOCK_THRESHOLD = $11,
  RESTOCK_QTY = $12,
  AUTO_ORDER = $13,
  SUPPLIER = $14,
  PRODUCT_TYPE = $15,
  PLU = $16
RETURNING INVENTORY_NAME;

-- SELECT FROM inventorylist
SELECT * FROM inventorylist WHERE INVENTORY_NAME = $1;

-- UPDATE inventorylist
UPDATE inventorylist SET
  PRODUCT_NAME = $2, PRODUCT_PORTION = $3
WHERE INVENTORY_NAME = $1;

-- DELETE FROM inventorylist
DELETE FROM inventorylist WHERE INVENTORY_NAME = $1;


-- CRUD Operations for productlist

-- INSERT INTO productlist
INSERT INTO productlist (
  PRODUCT_NAME, PACKAGE_SIZE, FULL_WEIGHT, EMPTY_WEIGHT, SUPPLIER, PRODUCT_TYPE
) VALUES (
  $1, $2, $3, $4, $5, $6
) ON CONFLICT (PRODUCT_NAME) DO UPDATE SET
  PACKAGE_SIZE = $2,
  FULL_WEIGHT = $3,
  EMPTY_WEIGHT = $4,
  SUPPLIER = $5,
  PRODUCT_TYPE = $6
RETURNING PRODUCT_NAME;

-- SELECT FROM productlist
SELECT * FROM productlist WHERE PRODUCT_NAME = $1;

-- UPDATE productlist
UPDATE productlist SET
  PACKAGE_SIZE = $2, FULL_WEIGHT = $3
WHERE PRODUCT_NAME = $1;

-- DELETE FROM productlist
DELETE FROM productlist WHERE PRODUCT_NAME = $1;


-- CRUD Operations for sales

-- INSERT INTO sales
INSERT INTO sales (
  ENTRY_DATE, EMPLOYEE, EXPECTED_SALES, ACTUAL_SALES, CASH_TRANSACTION,
  CARD_TRANSACTION, OTHER_TRANSACTION, DIFFERENCE, COMMENTS, UPDATE_DATE
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, CURRENT_DATE
) ON CONFLICT (ENTRY_DATE) DO UPDATE SET
  EMPLOYEE = $2,
  EXPECTED_SALES = $3,
  ACTUAL_SALES = $4,
  CASH_TRANSACTION = $5,
  CARD_TRANSACTION = $6,
  OTHER_TRANSACTION = $7,
  DIFFERENCE = $8,
  COMMENTS = $9,
  UPDATE_DATE = CURRENT_DATE
RETURNING ENTRY_DATE;

-- SELECT FROM sales
SELECT * FROM sales WHERE ENTRY_DATE = $1;

-- UPDATE sales
UPDATE sales SET
  ACTUAL_SALES = $2, DIFFERENCE = $3
WHERE ENTRY_DATE = $1;

-- DELETE FROM sales
DELETE FROM sales WHERE ENTRY_DATE = $1;


-- CRUD Operations for salesdata

-- INSERT INTO salesdata
INSERT INTO salesdata (
  ENTRY_DATE, INVENTORY_NAME, SOLD, LOSS, DIFFERENCE,
  START_STOCK, END_STOCK, BOTTLE_WEIGHT, COMMENTS, UPDATE_DATE
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, CURRENT_DATE
) ON CONFLICT (ENTRY_DATE) DO UPDATE SET
  INVENTORY_NAME = $2,
  SOLD = $3,
  LOSS = $4,
  DIFFERENCE = $5,
  START_STOCK = $6,
  END_STOCK = $7,
  BOTTLE_WEIGHT = $8,
  COMMENTS = $9,
  UPDATE_DATE = CURRENT_DATE
RETURNING ENTRY_DATE;

-- SELECT FROM salesdata
SELECT * FROM salesdata WHERE ENTRY_DATE = $1;

-- UPDATE salesdata
UPDATE salesdata SET
  SOLD = $2, END_STOCK = $3
WHERE ENTRY_DATE = $1 AND INVENTORY_NAME = $4;

-- DELETE FROM salesdata
DELETE FROM salesdata WHERE ENTRY_DATE = $1 AND INVENTORY_NAME = $2;


-- CRUD Operations for calibration

-- INSERT INTO calibration
INSERT INTO calibration (
  ENTRY_DATE, EMPLOYEE, CALIBRATION_DATA, COMMENTS
) VALUES (
  $1, $2, $3, $4
) ON CONFLICT (ENTRY_DATE) DO UPDATE SET
  EMPLOYEE = $2,
  CALIBRATION_DATA = $3,
  COMMENTS = $4
RETURNING ENTRY_DATE;

-- SELECT FROM calibration
SELECT * FROM calibration WHERE ENTRY_DATE = $1;

-- UPDATE calibration
UPDATE calibration SET
  CALIBRATION_DATA = $2, COMMENTS = $3
WHERE ENTRY_DATE = $1;

-- DELETE FROM calibration
DELETE FROM calibration WHERE ENTRY_DATE = $1;


-- CRUD Operations for supplierlist

-- INSERT INTO supplierlist
INSERT INTO supplierlist (
  SUPPLIER, EMAIL
) VALUES (
  $1, $2
) ON CONFLICT (SUPPLIER) DO UPDATE SET
  EMAIL = $2
RETURNING SUPPLIER;

-- SELECT FROM supplierlist
SELECT * FROM supplierlist WHERE SUPPLIER = $1;

-- UPDATE supplierlist
UPDATE supplierlist SET
  EMAIL = $2
WHERE SUPPLIER = $1;

-- DELETE FROM supplierlist
DELETE FROM supplierlist WHERE SUPPLIER = $1;


-- CRUD Operations for logs

-- INSERT INTO logs
INSERT INTO logs (
  EMPLOYEE, ENTRY_DATE, LOGS
) VALUES (
  $1, $2, $3
) ON CONFLICT (EMPLOYEE) DO UPDATE SET
  LOGS = $3,
  ENTRY_DATE = $2
RETURNING EMPLOYEE;

-- SELECT FROM logs
SELECT * FROM logs WHERE EMPLOYEE = $1;

-- UPDATE logs
UPDATE logs SET
  LOGS = $2
WHERE EMPLOYEE = $1 AND ENTRY_DATE = $3;

-- DELETE FROM logs
DELETE FROM logs WHERE EMPLOYEE = $1 AND ENTRY_DATE = $2;
