INSERT INTO inventorylist (INVENTORY_NAME, PRODUCT_NAME, QTY_DATA, LOW_STOCK_THRESHOLD, RESTOCK_QTY, AUTO_ORDER, SUPPLIER, PRODUCT_TYPE, PLU)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (INVENTORY_NAME) DO
UPDATE SET 
		PRODUCT_NAME = $2,
		QTY_DATA = $3,
		LOW_STOCK_THRESHOLD = $4,
		RESTOCK_QTY = $5,
		AUTO_ORDER = $6,
		SUPPLIER = $7,
		PRODUCT_TYPE = $8,
		PLU = $9
RETURNING INVENTORY_NAME;