INSERT INTO inventorylist (INVENTORY_NAME, PRODUCT_NAME, QTY_DATA, LOW_STOCK_THRESHOLD, AUTO_ORDER, SUPPLIER, PRODUCT_TYPE, PLU)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (INVENTORY_NAME) DO NOTHING
RETURNING INVENTORY_NAME;