INSERT INTO sales (ENTRY_DATE, EMPLOYEE, EXPECTED_SALES, ACTUAL_SALES, CASH_TRANSACTION, CARD_TRANSACTION, OTHER_TRANSACTION, DIFFERENCE, COMMENTS)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (ENTRY_DATE, EMPLOYEE) DO
UPDATE SET 
	EXPECTED_SALES = $3,
	ACTUAL_SALES = $4,
	CASH_TRANSACTION = $5,
	CARD_TRANSACTION = $6,
	OTHER_TRANSACTION = $7,
	DIFFERENCE = $8,
	COMMENTS = $9;