SELECT 
    INVENTORY_ID,
    INVENTORY_NAME,
    PRODUCT_ID,
    PRODUCT_PORTION,
    QTY_DATA,
    LOW_STOCK_THRESHOLD,
    RESTOCK_QTY,
    AUTO_ORDER,
    SUPPLIER_ID,
    PRODUCT_TYPE,
    PLU,
    LAST_UPDATE
FROM inventorylist
WHERE DELETED = false
  AND (INVENTORY_NAME ILIKE '%' || $3 || '%' OR PRODUCT_TYPE ILIKE '%' || $3 || '%') -- Optional search filter
ORDER BY LAST_UPDATE DESC
LIMIT $1 OFFSET $2;