-- Inventory List Table
CREATE TABLE IF NOT EXISTS inventorylist (
  INVENTORY_NAME VARCHAR(250) PRIMARY KEY NOT NULL,
  PRODUCT_NAME VARCHAR(250) NOT NULL,
  PRODUCT_NAME_1 VARCHAR(250) NULL,
  PRODUCT_NAME_2 VARCHAR(250) NULL,
  PRODUCT_NAME_3 VARCHAR(250) NULL,
  PRODUCT_PORTION SMALLINT DEFAULT 0,
  PRODUCT_PORTION_1 SMALLINT DEFAULT 0,
  PRODUCT_PORTION_2 SMALLINT DEFAULT 0,
  PRODUCT_PORTION_3 SMALLINT DEFAULT 0,
  QTY_DATA JSON,
  LOW_STOCK_THRESHOLD SMALLINT DEFAULT 0,
  RESTOCK_QTY SMALLINT DEFAULT 0,
  AUTO_ORDER BOOLEAN DEFAULT false,
  SUPPLIER VARCHAR(250),
  PRODUCT_TYPE VARCHAR(250) NOT NULL,
  PLU SMALLINT DEFAULT NULL,
  LAST_UPDATE DATE DEFAULT CURRENT_DATE
);

-- Indexes for inventorylist
CREATE INDEX idx_inventory_product_name ON inventorylist (PRODUCT_NAME);
CREATE INDEX idx_inventory_product_type ON inventorylist (PRODUCT_TYPE);
CREATE INDEX idx_inventory_supplier ON inventorylist (SUPPLIER);

-- Product List Table
CREATE TABLE IF NOT EXISTS productlist (
  PRODUCT_NAME VARCHAR(250) PRIMARY KEY NOT NULL,
  PACKAGE_SIZE SMALLINT DEFAULT NULL,
  FULL_WEIGHT DECIMAL DEFAULT NULL,
  EMPTY_WEIGHT DECIMAL DEFAULT NULL,
  SUPPLIER VARCHAR(250),
  PRODUCT_TYPE VARCHAR(250) NOT NULL
);

-- Indexes for productlist
CREATE INDEX idx_product_supplier ON productlist (SUPPLIER);
CREATE INDEX idx_product_type ON productlist (PRODUCT_TYPE);

-- Sales Table
CREATE TABLE IF NOT EXISTS sales (
  ENTRY_DATE DATE PRIMARY KEY DEFAULT CURRENT_DATE,
  EMPLOYEE VARCHAR(250) NOT NULL,
  EXPECTED_SALES DECIMAL DEFAULT 0,
  ACTUAL_SALES DECIMAL DEFAULT 0,
  CASH_TRANSACTION DECIMAL DEFAULT 0,
  CARD_TRANSACTION DECIMAL DEFAULT 0,
  OTHER_TRANSACTION DECIMAL DEFAULT 0,
  DIFFERENCE DECIMAL DEFAULT 0,
  COMMENTS TEXT,
  UPDATE_DATE DATE DEFAULT CURRENT_DATE
);

-- Indexes for sales
CREATE INDEX idx_sales_employee ON sales (EMPLOYEE);
CREATE INDEX idx_sales_entry_date ON sales (ENTRY_DATE);

-- Sales Data Table
CREATE TABLE IF NOT EXISTS salesdata (
  ENTRY_DATE DATE PRIMARY KEY DEFAULT CURRENT_DATE,
  INVENTORY_NAME VARCHAR(250) NOT NULL,
  SOLD DECIMAL DEFAULT 0,
  LOSS DECIMAL DEFAULT 0,
  DIFFERENCE DECIMAL DEFAULT 0,
  START_STOCK DECIMAL DEFAULT 0,
  END_STOCK DECIMAL DEFAULT 0,
  BOTTLE_WEIGHT DECIMAL DEFAULT 0,
  COMMENTS TEXT,
  UPDATE_DATE DATE DEFAULT CURRENT_DATE
);

-- Indexes for salesdata
CREATE INDEX idx_salesdata_inventory_name ON salesdata (INVENTORY_NAME);
CREATE INDEX idx_salesdata_entry_date ON salesdata (ENTRY_DATE);

-- Calibration Table
CREATE TABLE IF NOT EXISTS calibration (
  ENTRY_DATE DATE PRIMARY KEY DEFAULT CURRENT_DATE,
  EMPLOYEE VARCHAR(250) NOT NULL,
  CALIBRATION_DATA JSON,
  COMMENTS TEXT
);

-- Indexes for calibration
CREATE INDEX idx_calibration_employee ON calibration (EMPLOYEE);
CREATE INDEX idx_calibration_entry_date ON calibration (ENTRY_DATE);

-- Supplier List Table
CREATE TABLE IF NOT EXISTS supplierlist (
  SUPPLIER VARCHAR(250) PRIMARY KEY NOT NULL,
  EMAIL VARCHAR(250)
);

-- Indexes for supplierlist
CREATE INDEX idx_supplier_email ON supplierlist (EMAIL);

-- Logs Table
CREATE TABLE IF NOT EXISTS logs (
  EMPLOYEE VARCHAR(250) PRIMARY KEY NOT NULL,
  ENTRY_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
  LOGS TEXT
);

-- Indexes for logs
CREATE INDEX idx_logs_employee ON logs (EMPLOYEE);
CREATE INDEX idx_logs_entry_date ON logs (ENTRY_DATE);
