-- Supplier List Table
CREATE TABLE IF NOT EXISTS supplierlist (
  SUPPLIER_ID SERIAL PRIMARY KEY, -- Added surrogate key for better indexing
  SUPPLIER_NAME VARCHAR(250) NOT NULL UNIQUE,
  EMAIL VARCHAR(250) UNIQUE,
  DELETED BOOLEAN DEFAULT false -- Added for soft deletes
);

-- Product List Table
CREATE TABLE IF NOT EXISTS productlist (
  PRODUCT_ID SERIAL PRIMARY KEY,
  PRODUCT_NAME VARCHAR(250) NOT NULL UNIQUE,
  PACKAGE_SIZE SMALLINT DEFAULT NULL,
  FULL_WEIGHT DECIMAL(10, 2) DEFAULT NULL,
  EMPTY_WEIGHT DECIMAL(10, 2) DEFAULT NULL,
  SUPPLIER_ID INT, -- Foreign key to supplierlist
  PRODUCT_TYPE VARCHAR(250) NOT NULL,
  DELETED BOOLEAN DEFAULT false, -- Added for soft deletes
  CONSTRAINT fk_product_supplier FOREIGN KEY (SUPPLIER_ID) REFERENCES supplierlist(SUPPLIER_ID) ON DELETE SET NULL,
  CONSTRAINT chk_full_weight CHECK (FULL_WEIGHT >= 0),
  CONSTRAINT chk_empty_weight CHECK (EMPTY_WEIGHT >= 0)
);

-- Inventory List Table
CREATE TABLE IF NOT EXISTS inventorylist (
  INVENTORY_ID SERIAL PRIMARY KEY,
  INVENTORY_NAME VARCHAR(250) NOT NULL UNIQUE,
  PRODUCT_ID INT NOT NULL, -- Foreign key to productlist
  PRODUCT_PORTION SMALLINT DEFAULT 0,
  QTY_DATA JSON,
  LOW_STOCK_THRESHOLD SMALLINT DEFAULT 0,
  RESTOCK_QTY SMALLINT DEFAULT 0,
  AUTO_ORDER BOOLEAN DEFAULT false,
  SUPPLIER_ID INT, -- Foreign key to supplierlist
  PRODUCT_TYPE VARCHAR(250) NOT NULL,
  PLU SMALLINT DEFAULT NULL,
  LAST_UPDATE DATE DEFAULT CURRENT_DATE,
  DELETED BOOLEAN DEFAULT false, -- Added for soft deletes
  CONSTRAINT fk_inventory_product FOREIGN KEY (PRODUCT_ID) REFERENCES productlist(PRODUCT_ID) ON DELETE CASCADE,
  CONSTRAINT fk_inventory_supplier FOREIGN KEY (SUPPLIER_ID) REFERENCES supplierlist(SUPPLIER_ID) ON DELETE SET NULL,
  CONSTRAINT chk_low_stock CHECK (LOW_STOCK_THRESHOLD >= 0),
  CONSTRAINT chk_restock_qty CHECK (RESTOCK_QTY >= 0),
  CONSTRAINT chk_restock_threshold CHECK (RESTOCK_QTY > LOW_STOCK_THRESHOLD)
);

-- Junction Table for Inventory and Multiple Products
CREATE TABLE IF NOT EXISTS inventory_products (
  INVENTORY_ID INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  PRODUCT_PORTION SMALLINT DEFAULT 0,
  CONSTRAINT fk_inventory FOREIGN KEY (INVENTORY_ID) REFERENCES inventorylist(INVENTORY_ID) ON DELETE CASCADE,
  CONSTRAINT fk_product FOREIGN KEY (PRODUCT_ID) REFERENCES productlist(PRODUCT_ID) ON DELETE CASCADE,
  PRIMARY KEY (INVENTORY_ID, PRODUCT_ID)
);

-- Sales Table
CREATE TABLE IF NOT EXISTS sales (
  ENTRY_DATE DATE PRIMARY KEY DEFAULT CURRENT_DATE,
  EMPLOYEE VARCHAR(250) NOT NULL,
  EXPECTED_SALES DECIMAL(10, 2) DEFAULT 0,
  ACTUAL_SALES DECIMAL(10, 2) DEFAULT 0,
  CASH_TRANSACTION DECIMAL(10, 2) DEFAULT 0,
  CARD_TRANSACTION DECIMAL(10, 2) DEFAULT 0,
  OTHER_TRANSACTION DECIMAL(10, 2) DEFAULT 0,
  DIFFERENCE DECIMAL(10, 2) DEFAULT 0,
  COMMENTS TEXT DEFAULT '',
  UPDATE_DATE DATE DEFAULT CURRENT_DATE
);

-- Sales Data Table
CREATE TABLE IF NOT EXISTS salesdata (
  ENTRY_DATE DATE PRIMARY KEY DEFAULT CURRENT_DATE,
  INVENTORY_ID INT NOT NULL, -- Foreign key to inventorylist
  SOLD DECIMAL(10, 2) DEFAULT 0,
  LOSS DECIMAL(10, 2) DEFAULT 0,
  DIFFERENCE DECIMAL(10, 2) DEFAULT 0,
  START_STOCK DECIMAL(10, 2) DEFAULT 0,
  END_STOCK DECIMAL(10, 2) DEFAULT 0,
  BOTTLE_WEIGHT DECIMAL(10, 2) DEFAULT 0,
  COMMENTS TEXT DEFAULT '',
  UPDATE_DATE DATE DEFAULT CURRENT_DATE,
  DELETED BOOLEAN DEFAULT false, -- Added for soft deletes
  CONSTRAINT fk_salesdata_inventory FOREIGN KEY (INVENTORY_ID) REFERENCES inventorylist(INVENTORY_ID) ON DELETE CASCADE
);

-- Calibration Table
CREATE TABLE IF NOT EXISTS calibration (
  ENTRY_DATE DATE PRIMARY KEY DEFAULT CURRENT_DATE,
  EMPLOYEE VARCHAR(250) NOT NULL,
  CALIBRATION_DATA JSON,
  COMMENTS TEXT DEFAULT ''
);

-- Logs Table
CREATE TABLE IF NOT EXISTS logs (
  LOG_ID SERIAL PRIMARY KEY,
  EMPLOYEE VARCHAR(250) NOT NULL,
  ENTRY_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
  LOGS TEXT DEFAULT ''
);

-- Audit Log Table
CREATE TABLE audit_log (
  LOG_ID SERIAL PRIMARY KEY,
  TABLE_NAME VARCHAR(100),
  OPERATION VARCHAR(10),
  OLD_DATA JSON,
  NEW_DATA JSON,
  TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_inventory_product_id ON inventorylist (PRODUCT_ID);
CREATE INDEX IF NOT EXISTS idx_inventory_product_type ON inventorylist (PRODUCT_TYPE);
CREATE INDEX IF NOT EXISTS idx_inventory_supplier ON inventorylist (SUPPLIER_ID);
CREATE INDEX IF NOT EXISTS idx_inventory_low_stock ON inventorylist (LOW_STOCK_THRESHOLD);
CREATE INDEX IF NOT EXISTS idx_product_type ON productlist (PRODUCT_TYPE);
CREATE INDEX IF NOT EXISTS idx_sales_employee ON sales (EMPLOYEE);
CREATE INDEX IF NOT EXISTS idx_sales_entry_date ON sales (ENTRY_DATE);
CREATE INDEX IF NOT EXISTS idx_salesdata_inventory_id ON salesdata (INVENTORY_ID);
CREATE INDEX IF NOT EXISTS idx_logs_employee ON logs (EMPLOYEE);
CREATE INDEX IF NOT EXISTS idx_logs_entry_date ON logs (ENTRY_DATE);

-- Add DELETED column to other tables
ALTER TABLE sales ADD COLUMN EMPLOYEE_ID INT;
ALTER TABLE sales ADD CONSTRAINT fk_sales_employee FOREIGN KEY (EMPLOYEE_ID) REFERENCES employees(EMPLOYEE_ID) ON DELETE SET NULL;
ALTER TABLE supplierlist ADD COLUMN IF NOT EXISTS DELETED BOOLEAN DEFAULT false;
ALTER TABLE productlist ADD COLUMN IF NOT EXISTS DELETED BOOLEAN DEFAULT false;
ALTER TABLE salesdata ADD COLUMN IF NOT EXISTS DELETED BOOLEAN DEFAULT false;

-- Soft Delete Trigger for inventorylist
CREATE OR REPLACE FUNCTION log_soft_delete_inventory()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO audit_log (TABLE_NAME, OPERATION, OLD_DATA, TIMESTAMP)
  VALUES ('inventorylist', 'SOFT_DELETE', row_to_json(OLD), CURRENT_TIMESTAMP);
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_soft_delete_inventory
AFTER UPDATE OF DELETED ON inventorylist
FOR EACH ROW
WHEN (NEW.DELETED = true)
EXECUTE FUNCTION log_soft_delete_inventory();

-- Soft Delete Trigger for productlist
CREATE OR REPLACE FUNCTION log_soft_delete_product()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO audit_log (TABLE_NAME, OPERATION, OLD_DATA, TIMESTAMP)
  VALUES ('productlist', 'SOFT_DELETE', row_to_json(OLD), CURRENT_TIMESTAMP);
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_soft_delete_product
AFTER UPDATE OF DELETED ON productlist
FOR EACH ROW
WHEN (NEW.DELETED = true)
EXECUTE FUNCTION log_soft_delete_product();

-- Views for active records
CREATE OR REPLACE VIEW active_inventorylist AS
SELECT * FROM inventorylist WHERE DELETED = false;

CREATE OR REPLACE VIEW active_productlist AS
SELECT * FROM productlist WHERE DELETED = false;

-- General Change Logging Trigger
CREATE OR REPLACE FUNCTION log_changes_inventory()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO audit_log (TABLE_NAME, OPERATION, OLD_DATA, NEW_DATA, TIMESTAMP)
  VALUES ('inventorylist', TG_OP, row_to_json(OLD), row_to_json(NEW), CURRENT_TIMESTAMP);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_log_changes_inventory
AFTER INSERT OR UPDATE OR DELETE ON inventorylist
FOR EACH ROW
EXECUTE FUNCTION log_changes_inventory();
