CREATE TABLE IF NOT EXISTS inventorylist (
  INVENTORY_NAME VARCHAR(250) PRIMARY KEY NOT NULL,
	PRODUCT_NAME VARCHAR(250) NOT NULL,
	PRODUCT_NAME_1 VARCHAR(250) NULL,
	PRODUCT_NAME_2 VARCHAR(250) NULL,
	PRODUCT_NAME_3 VARCHAR(250) NULL,
	PRODUCT_PORTION SMALLINT DEFAULT 0,
	PRODUCT_PORTION_1 SMALLINT DEFAULT 0,
	PRODUCT_PORTION_2 SMALLINT DEFAULT 0,
	PRODUCT_PORTION_3 SMALLINT DEFAULT 0,
	QTY_DATA JSON,
	LOW_STOCK_THRESHOLD SMALLINT DEFAULT 0,
	RESTOCK_QTY SMALLINT DEFAULT 0,
	AUTO_ORDER BOOLEAN DEFAULT false,
	SUPPLIER VARCHAR(250),
	PRODUCT_TYPE VARCHAR(250) NOT NULL,
	PLU SMALLINT DEFAULT NULL,
	LAST_UPDATE DATE DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS productlist (
  PRODUCT_NAME VARCHAR(250) PRIMARY KEY NOT NULL,
	PACKAGE_SIZE SMALLINT DEFAULT NULL,
	FULL_WEIGHT DECIMAL DEFAULT NULL,
	EMPTY_WEIGHT DECIMAL DEFAULT NULL,
	SUPPLIER VARCHAR(250),
	PRODUCT_TYPE VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS sales (
	ENTRY_DATE DATE PRIMARY KEY DEFAULT CURRENT_DATE,
	EMPLOYEE VARCHAR(250) NOT NULL,
	SALES_DATA JSON,
	SALES_NUMBERS JSON,
	COMMENTS TEXT
);

CREATE TABLE IF NOT EXISTS calibration (
	ENTRY_DATE DATE PRIMARY KEY DEFAULT CURRENT_DATE,
	EMPLOYEE VARCHAR(250) NOT NULL,
	CALIBRATION_DATA JSON,
	QTY_DATA JSON,
	COMMENTS TEXT
);

CREATE TABLE IF NOT EXISTS supplierlist (
	SUPPLIER VARCHAR(250) PRIMARY KEY NOT NULL,
	EMAIL VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS logs (
	EMPLOYEE VARCHAR(250) PRIMARY KEY NOT NULL,
	ENTRY_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
	LOGS TEXT
);
