CREATE TABLE IF NOT EXISTS inventory (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
	PRODUCT_NAME VARCHAR(250) NOT NULL,
	PACKAGE_SIZE SMALLINT,
	SUPPLIER VARCHAR(250),
	PLU SMALLINT,
	UPDATE_DATE DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS productlist (
  ID SERIAL PRIMARY KEY,
  PRODUCT_NAME VARCHAR(250) NOT NULL,
	PACKAGE_SIZE SMALLINT,
	FULL_WEIGHT DECIMAL DEFAULT 0,
	EMPTY_WEIGHT DECIMAL DEFAULT 0,
	SUPPLIER VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS sales (
	EMPLOYEE VARCHAR(250) NOT NULL,
	ENTRY_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
	SALES_DATA TEXT NOT NULL,
	SALES_NUMBERS TEXT NOT NULL,
	COMMENTS TEXT
);

CREATE TABLE IF NOT EXISTS calibration (
	EMPLOYEE VARCHAR(250) NOT NULL,
	ENTRY_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
	CALIBRATION TEXT,
	COMMENTS TEXT
);

CREATE TABLE IF NOT EXISTS supplierlist (
	SUPPLIER VARCHAR(250) NOT NULL,
	EMAIL VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS logs (
	EMPLOYEE VARCHAR(250) NOT NULL,
	ENTRY_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
	LOGS TEXT
);
